# Generated by Django 4.2.6 on 2023-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default="", null=True)),
                ("pin", models.IntegerField(blank=True, default="", null=True)),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="upload/users"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="pic1",
            field=models.ImageField(upload_to="upload/product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic2",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="upload/product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic3",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="upload/product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic4",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="upload/product"
            ),
        ),
    ]
