# Generated by Django 4.2.6 on 2023-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_buyer_alter_product_pic1_alter_product_pic2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="phone",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
