# Generated by Django 4.2.6 on 2023-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_buyer_phone_alter_buyer_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
    ]
