# Generated by Django 4.2.6 on 2023-11-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_checkout_checkoutproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="subcategory",
            new_name="subtotal",
        ),
    ]
