# Generated by Django 4.2.6 on 2023-11-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_contact_newslatter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("message", models.TextField()),
                ("pic", models.ImageField(upload_to="upload/testimonials")),
            ],
        ),
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
