# Generated by Django 4.2.6 on 2023-11-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_testimonial_buyer_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
