# Generated by Django 4.2.6 on 2023-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_buyer_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
